#!/bin/sh
#
# This file was produced by running the Configure script. It holds all the
# definitions figured out by Configure. Should you modify one of these values,
# do not forget to propagate your changes by running "Configure -der". You may
# instead choose to run each of the .SH files by yourself, or "Configure -S".
#

# Package name      : IPC-ShareLite
# Source directory  : .
# Configuration time: Tue Apr  4 15:04:49 MDT 2006
# Configured by     : root
# Target system     : linux soundwave 2.6.15.5-rubix #1 smp fri mar 3 11:01:24 mst 2006 i686 gnulinux 

Author=''
Date=''
Header=''
Id=''
Locker=''
Log=''
Mcc=''
RCSfile=''
Revision=''
Source=''
State=''
ar=''
archobjs=''
awk='awk'
bash=''
bison=''
byacc=''
c=''
cat='cat'
cf_by='root'
cf_time='Tue Apr  4 15:04:49 MDT 2006'
chgrp=''
chmod=''
chown=''
comm=''
compress=''
contains='grep'
cp=''
cpio=''
cpp='cpp'
cpplast='-'
cppminus='-'
cpprun='cc -E'
cppstdin='cc -E'
csh=''
d_bsd='undef'
d_eunice='undef'
d_gnulibc='undef'
d_portable='define'
d_sem='undef'
d_semctl='undef'
d_semctl_semid_ds='undef'
d_semctl_semun='undef'
d_semget='undef'
d_semop='undef'
d_union_semun='undef'
d_xenix='undef'
date='date'
defvoidused='15'
echo='echo'
egrep=''
emacs=''
eunicefix=':'
expr='expr'
find=''
firstmakefile=''
flex=''
gcc=''
glibpth='/shlib /usr/shlib /lib/pa1.1 /usr/lib/large /lib /usr/lib /usr/lib/386 /lib/386 /lib/large /usr/lib/small /lib/small /usr/ccs/lib /usr/ucblib /usr/local/lib'
grep='grep'
gzip=''
hint='previous'
incpath=''
inews=''
ksh=''
less=''
libc='/usr/lib/libc.so'
libpth='/usr/local/lib /lib /usr/lib'
libs=' '
line=''
lint=''
ln='ln'
lns='/usr/bin/ln -s'
loclibpth='/usr/local/lib /opt/local/lib /usr/gnu/lib /opt/gnu/lib /usr/GNU/lib /opt/GNU/lib'
lp=''
lpr=''
ls=''
mail=''
mailx=''
make=''
mips=''
mips_type=''
mkdir=''
more=''
mv=''
myuname='linux soundwave 2.6.15.5-rubix #1 smp fri mar 3 11:01:24 mst 2006 i686 gnulinux '
n='-n'
nm_opt=''
nm_so_opt='--dynamic'
nroff=''
osname=''
osvers=''
package='IPC-ShareLite'
perl=''
pg=''
plibpth=''
pmake=''
pr=''
rm='rm'
rmail=''
runnm='true'
sed='sed'
sendmail=''
sh='/bin/sh'
shar=''
sharpbang='#!'
shsharp='true'
sleep=''
smail=''
so='so'
sort=''
spackage=''
spitshell='cat'
src='.'
startsh='#!/bin/sh'
submit=''
tail=''
tar=''
tbl=''
test='test'
touch='touch'
tr='tr'
troff=''
uname='uname'
uniq=''
usenm='true'
usrinc='/usr/include'
uuname=''
vi=''
voidflags='15'
xlibpth='/usr/lib/386 /lib/386'
zcat=''
zip=''
CONFIG=true
