#!/bin/bash

APMD_OPTS=""
SCRIPT=`basename $0`
PROG=/usr/sbin/apmd

. /etc/rubixlib
case "$1" in
	start)
		if [ ! -r /proc/apm -a ! -r /proc/acpi/info ]; then
			stat_busy "loading apm module"
			modprobe apm
			if [ $? -ne 0 ]; then
				stat_fail
				exit 1
			fi
			stat_done
		fi
		start_daemon $SCRIPT $PROG $APMD_OPTS
		;;
	stop)
		stop_daemon $SCRIPT $PROG
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		daemon_status $SCRIPT $PROG
		;;
	*)
		stat_err "usage: $0 {start|stop|restart|status}"
esac
