post_install() {

	VVER24=2.4.32
	GVER24=2.4.32-grsec
	VVER26=2.6.16.20-Rubix
	XVER26=2.6.16.20-XenRubix

	for kernel in $VVER24 $GVER24 $VVER26 $XVER26; do
		depmod -a -e -F boot/System.map-$kernel $kernel > /dev/null 2>&1
	done

	rm -f usr/X11R7/lib/libGL.so*
	cp -a usr/X11R7/lib/opengl/nvidia/* usr/X11R7/lib
	cp -a usr/X11R7/lib/modules/extensions/nvidia/* usr/X11R7/lib/modules/extensions

}

post_upgrade() {
	post_install $1
}

op=$1
shift
$op $*
