#!/bin/bash

GPM_ARGS="-m /dev/mouse -t imps2"

SCRIPT=`basename $0`
PROG=/usr/sbin/gpm

. /etc/rubixlib
case "$1" in
	start)
		start_daemon $SCRIPT $PROG $GPM_ARGS
		;;
	stop)
		stop_daemon $SCRIPT $PROG
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		daemon_status $SCRIPT $PROG
		;;
	*)
		stat_err "usage: $0 {start|stop|restart|status}"
esac
