#!/bin/bash

SCRIPT=`basename $0`
PROG=/usr/sbin/dansguardian

. /etc/rubixlib
case "$1" in
	start)
		start_daemon $SCRIPT $PROG
		;;
	stop)
		stop_daemon $SCRIPT $PROG
		;;
	restart)
		$0 stop
		sleep 5
		$0 start
		;;
	status)
		daemon_status $SCRIPT $PROG
		;;
	*)
		stat_err "usage: $0 {start|stop|restart|status}"
esac
