#!/bin/bash

SPAMD_OPTS="-c"

SCRIPT=`basename $0`
PROG=/usr/bin/spamd

. /etc/rubixlib
case "$1" in
	start)
		start_daemon $SCRIPT $PROG -d $SPAMD_OPTS
		;;
	stop)
		stop_daemon $SCRIPT $PROG
		;;
	restart)
		$0 stop
		sleep 3
		$0 start
		;;
	status)
		daemon_status $SCRIPT $PROG
		;;
	*)
		stat_err "usage: $0 {start|stop|restart|status}"
esac
