#!/bin/bash

SASLAUTHD_OPTS="-a shadow"
SCRIPT=`basename $0`
PROG=/usr/sbin/saslauthd

. /etc/rubixlib
case "$1" in
	start)
		start_daemon $SCRIPT $PROG $SASLAUTHD_OPTS
		;;
	stop)
		stop_daemon $SCRIPT $PROG
		;;
	restart)
		$0 stop
		sleep 1
		$0 start
		;;
	status)
		daemon_status $SCRIPT $PROG
		;;
	*)
		stat_err "usage: $0 {start|stop|restart|status}"
esac
