post_install() {

	if ! grep '/bin/tcsh' etc/shells 1> /dev/null 2> /dev/null ; then
		echo "/bin/tcsh" >> etc/shells
	fi

	if ! grep '/bin/csh' etc/shells 1> /dev/null 2> /dev/null ; then
		echo "/bin/csh" >> etc/shells
	fi
}

post_upgrade() {
	post_install
}

pre_remove() {
        cat etc/shells | grep -v '/bin/csh' | grep -v '/bin/tcsh' > tmp/pacash
        cat tmp/pacash > etc/shells
        sbin/ldconfig -r .
}

op=$1
shift
$op $*
